import Head from 'next/head';
import { GetServerSideProps, GetStaticProps, NextPage } from 'next';
import { posts } from './api/notion';
import Link from 'next/link';

interface Props {
  posts: [any];
}

const Home: NextPage<Props> = (props) => {
  return (
    <>
      <Head>
        <title>Young Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {
          props.posts.map((result, i) => (
            <div key={i}>
              <Link href={`/${result.id}`}>
                {result.properties.Name.title[0].plain_text}
              </Link>
            </div>
          ))
        }
      </div>
    </>
  );
};

export default Home;

export const getStaticProps = async () => {
  let { results } = await posts();
  return {
    props: {
      posts: results
    },
    revalidate: 1,
  };
};